/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author srivenkatasatyaakhilmalladi
 */
public class PrimaryJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrimaryJFrame
     */
    public PrimaryJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        Primary_ControlPanel = new javax.swing.JPanel();
        Bdoctor = new javax.swing.JButton();
        Bpatient = new javax.swing.JButton();
        Bcommunity = new javax.swing.JButton();
        Bsysadmin = new javax.swing.JButton();
        BHospital = new javax.swing.JButton();
        Login_Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bdoctor.setText("Doctor");

        Bpatient.setText("Patient");
        Bpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpatientActionPerformed(evt);
            }
        });

        Bcommunity.setText("Community");

        Bsysadmin.setText("Sys Admin");
        Bsysadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsysadminActionPerformed(evt);
            }
        });

        BHospital.setText("Hospital");

        javax.swing.GroupLayout Primary_ControlPanelLayout = new javax.swing.GroupLayout(Primary_ControlPanel);
        Primary_ControlPanel.setLayout(Primary_ControlPanelLayout);
        Primary_ControlPanelLayout.setHorizontalGroup(
            Primary_ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Primary_ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Primary_ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bcommunity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bpatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bdoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bsysadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        Primary_ControlPanelLayout.setVerticalGroup(
            Primary_ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Primary_ControlPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Bdoctor)
                .addGap(51, 51, 51)
                .addComponent(Bpatient)
                .addGap(55, 55, 55)
                .addComponent(Bcommunity)
                .addGap(52, 52, 52)
                .addComponent(BHospital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(Bsysadmin)
                .addGap(51, 51, 51))
        );

        SplitPane.setRightComponent(Primary_ControlPanel);

        javax.swing.GroupLayout Login_PanelLayout = new javax.swing.GroupLayout(Login_Panel);
        Login_Panel.setLayout(Login_PanelLayout);
        Login_PanelLayout.setHorizontalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Login_PanelLayout.setVerticalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        SplitPane.setLeftComponent(Login_Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BpatientActionPerformed

    private void BsysadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsysadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BsysadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimaryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimaryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimaryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimaryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimaryJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHospital;
    private javax.swing.JButton Bcommunity;
    private javax.swing.JButton Bdoctor;
    private javax.swing.JButton Bpatient;
    private javax.swing.JButton Bsysadmin;
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JPanel Primary_ControlPanel;
    private javax.swing.JSplitPane SplitPane;
    // End of variables declaration//GEN-END:variables
}
